### ISSUE TITLE
Strange JavaScript indenting

### ISSUE THREAD

**Issue by wukkuan** [fxbois/web-mode#564]
Braces don't seem to indent themselves as I'd expect. For example, if I type `function test() {<enter>}` I expect the result to be:

```javascript
function test() {
}
```

But the actual result is:

```javascript
function test() {
	}
```
This necessitates that I manually unindent the `}` line. Is this on purpose? Is there a way to configure around that or a better workflow that you intended?

## Configuration details
* Emacs 24.5.1, OS X 10.10.4
* Fresh `.emacs.d` directory
* web-mode installed via melpa
* `web-mode-content-type` set to `jsx` via `web-mode-content-types-alist` (see `.emacs` below)

### .emacs
```elisp
;;; Melpa (copy/pasted from their docs)
(require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) ;; You might already have this line

;;; web-mode
(add-to-list 'auto-mode-alist '("\\.js[x]?\\'" . web-mode))
(setq web-mode-content-types-alist
  '(("jsx"  . "\\.js[x]?\\'")))
```

**Comment by fxbois** [comment]
@wukkuan I do not have this issue ... it must be related to a minor mode

**Comment by wukkuan** [comment]
You may be right! But if so, it must be a minor mode that's on by default in Emacs 24.5.1. Here is the output of `describe-mode`:

> Enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption
> Electric-Indent File-Name-Shadow Font-Lock Global-Font-Lock
> Line-Number Menu-Bar Mouse-Wheel Tool-Bar Tooltip Transient-Mark

`electric-indent` could be the culprit? It was enabled by default in 24.4. Turning it off kind of fixes it, but the behavior is still not what I expect.

Perhaps the problem is that my behavior expectation isn't what yours is. If so, that's my problem not yours! The big thing I'm expecting is for an indented `}` to unindent itself after typing.

**Comment by fxbois** [comment]
The behaviour on my my machine is the one described on your first post : ```}``` at the beginning of the line ... it is strange

could you post the output of web-mode-debug ?

**Comment by wukkuan** [comment]
```
For information about GNU Emacs and the GNU system, type C-h C-a. [2 times]
test.js has auto save data; consider M-x recover-this-file
 [2 times]
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.5) web-mode("12.0.2")
vars: engine("none") minor("none") content-type("jsx") file("/Users/blasko/test.js")
system: window(mac) config("x86_64-apple-darwin14.4.0")
colors: fg(nil) bg(nil) 
minor modes: (mac-mouse-wheel-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=t 
--- WEB-MODE DEBUG END ---
```

**Comment by fxbois** [comment]
@wukkuan does it changes anything when you add ```(setq-default indent-tabs-mode nil) ``` ?

**Comment by wukkuan** [comment]
No, same behavior.

**Comment by fxbois** [comment]
I can not reproduce this bug. I'll look at it if I have an other report like this

**Comment by davebrown** [comment]
Same problem as @wukkuan reported in August. In `web-mode` I get this behavior:

![web-mode-indent](https://cloud.githubusercontent.com/assets/455354/21906895/1217e130-d8c2-11e6-9e36-fe8489b6dbf1.gif)

In `js-mode` the closing brace indents as expected:

![js-mode-indent](https://cloud.githubusercontent.com/assets/455354/21906925/31e58832-d8c2-11e6-8ea0-2d3fde1ee83c.gif)

My environment:

- **web-mode-version**: 14.0.35
- **OS Version**: OS X Sierra 10.12.2
- **Emacs version**: 25.1

Tried with a minimal .emacs file like so, same result:

```lisp
(add-to-list 'load-path "~/.emacs.d/site-lisp/")
(require 'web-mode)
(setq auto-mode-alist
      (append '(("\\.jsx$" . web-mode)
                ) auto-mode-alist))
```

@fxbois I was going to file a new bug, but first looked to see if this had been reported previously, and found this. Thanks for the great package, and any help you can provide. Happy to pursue more diagnostics on my end if it'll help.

**Comment by davebrown** [comment]
I just noticed that hitting `<enter>` after `}` *does* fix the indent:
![web-mode-indent-fix-after-newline](https://cloud.githubusercontent.com/assets/455354/21907690/6cea4384-d8c5-11e6-9212-33ea85d24e2b.gif)

Perhaps a stylistic difference; I typically close a new block with `}`, then navigate up a line to fill it in, which happens in other modes.

Also, output of web-mode-debug:

```
--- WEB-MODE DEBUG BEG ---
versions: emacs(25.1) web-mode("14.0.35")
vars: engine("none") minor("none") content-type("jsx") file("/Users/dave/code/fruit-faces/src/components/FFDataVictory.jsx")
system: window(ns) config("x86_64-apple-darwin13.4.0")
colors: fg("lightGray") bg("black") 
minor modes: (global-eldoc-mode diff-auto-refine-mode)
vars:
web-mode-enable-current-column-highlight=nil 
web-mode-enable-current-element-highlight=nil 
indent-tabs-mode=nil 
--- WEB-MODE DEBUG END ---
```

**Comment by fxbois** [comment]
@wukkuan @davebrown I've just pushed a fix

**Comment by davebrown** [comment]
@fxbois hmm, I pulled web-mode.el as of revision 8139cf (double checked that I have your added text from [this rev](https://github.com/fxbois/web-mode/commit/8139cfa03dc80d78c258147095eb4204b2f75be8) ) restarted with minimal .emacs file as above, and still get the same behavior.
![web-mode-indent-with-fix-8139cf](https://cloud.githubusercontent.com/assets/455354/21934115/10e9a866-d95d-11e6-8d4a-27bdbca80760.gif)
