### ISSUE TITLE
region comment not work well if exist ERB tags.

### ISSUE THREAD

**Issue by zw963** [fxbois/web-mode#565]
```html
<select name="name" multiple="multiple">
  <li><% Time.now %></li>
  <li>Three </li>
</select>
```

if setting ``(setq web-mode-comment-style 2)``
use region select all content, run `web-mode-comment-or-uncomment`,
it will result in:

```html
<%# <select name="name" multiple="multiple">
<li><% Time.now %></li>
<li>Three </li>
</select> %>
```

this result to output result:
```html
</li>
<li>Three </li>
</select> %>
```

**Comment by fxbois** [comment]
@zw963 should be better with last version

**Comment by zw963** [comment]
Thanks, But still not work.

```html
<%= render 'sidebar' %>
```

comment one line,  and uncomment, will left
```html
= render 'sidebar' 
```

**Comment by fxbois** [comment]
there is no solution 
<%# <span>hello</span> %> -->  <span>hello</span>
<%# Time.now %> --> ?? how can I guess that in this case I should only remove the # 
I think I ll remove the patch i submitted for your issue ... this way the second case will work as before

**Comment by fxbois** [comment]
I've pushed an other patch

**Comment by zw963** [comment]
I think maybe can ```<%# hello %>`` just leave `hello` here.
any one add this comment will remove this immediately.

**Comment by zw963** [comment]
Oh, I wrong,  only remove ``#`` is right.

**Comment by zw963** [comment]
Hi, Thanks for yours fix, but still exist some problem.

In many case, if commented text exist erb block  will result in syntax error.

```html
  <tbody id="notifications">
    <% @notifications.each do |notification| %>
      <tr id="<%= dom_id(notification) %>"
      <td><%= notification.message %></td>
      </tr>
    <% end %>
  </tbody>
```

block comment all content, will result in:

```html
  <%# <tbody id="notifications">
  <% @notifications.each do |notification| %>
  <tr id="<%= dom_id(notification) %>"
  <td><%= notification.message %></td>
  </tr>
  <% end %>                <== here exist syntax error.
  </tbody> %>
```

block comment inner block, will result in:

```html  
  <tbody id="notifications">
    <%# @notifications.each do |notification| %>    < = only comment this line.
      <tr id="<%= dom_id(notification) %>"
      <td><%= notification.message %></td>
      </tr>
    <% end %>
  </tbody>
```

**Comment by fxbois** [comment]
@zw963 I do not understand your problem and what you want

**Comment by zw963** [comment]
Sorry for pool english.

general speaking, in following situation, comment is not work.

###  if a `<% ??? %> syntax is inside marked region.
```html
before comment:
<div id="id" class="class">
<%= Time.now %>
</div> 

after comment:
<%# <div id="id" class="class">
<%= Time.now %>
</div>  %>
```
this will output ``%> `` only.

### if a `ruby block` inside marked region, it not consider <% end %> situation
this will result in syntax error.

**Comment by fxbois** [comment]
element rename: ```C-c C-e r```

**Comment by fxbois** [comment]
for the previous comment, I have no solution .. you should use html comments

**Comment by zw963** [comment]
Hi, I found html comment have problem too.

```html
  <div>
    <label for="return_logistics_number">上传凭证:</label>
    <!-- <input type="file" class="form-control" id="return_logistics_image" name="return_logistics_image" data-url="server/php/" required multiple /> -->
  </div>
```

I select all content, add comment. will result in
```html
  <!-- <div>
       <label for="return_logistics_number">上传凭证:</label>
       <!-- <input type="file" class="form-control" id="return_logistics_image" name="return_logistics_image" data-url="server/php/" required multiple /> -->
</div> -->

```

**Comment by fxbois** [comment]
Comments inside comment are not allowed.
Moreover removing the inside comments would not be a good idea.
So I won't work on this

**Comment by zw963** [comment]
Cool ! Thanks.

**Comment by zw963** [comment]
comment in js is not worked?


```js
<script type="text/javascript" charset="utf-8">
  $(function () {
  // mark next line as region.
 alert('hello');
});
</script>
```
result:
```js
<script type="text/javascript" charset="utf-8">
  $(function () {
  // mark following line add comment.
 /*alert('hello');
});
</script>
```

**Comment by zw963** [comment]
I marked the full line, include the line end `\n`

**Comment by zw963** [comment]
when I mark following ` // $('#fileupload').fileupload();`
```js
<script type="text/javascript" charset="utf-8">
  $(function () {
    // Initialize the jQuery File Upload widget:
    alert($('#fileupload').length)
    // $('#fileupload').fileupload();
    // alert('world');
    //
  });
</script>
```

try uncomment it, will result in uncomment all following lines.

```js
<script type="text/javascript" charset="utf-8">
  $(function () {
    // Initialize the jQuery File Upload widget:
    alert($('#fileupload').length)
      $('#fileupload').fileupload();
    alert('world');
    
  });
</script>

```

**Comment by zw963** [comment]
Add a comment in javascript is not worked too.

```html
<script>
  asdfadsfas;
  asdfasdf;
  asdfas;
</script>
```

select second line and add a comment, will result in:
<script>
  asdfadsfas;
  /*asdfasdf;
  asdfas;
</script>

**Comment by zw963** [comment]
I have a question, could you design web-mode comment functionality to always use 
one-line comment ?? 

this situation is common for other model, e.g. in ruby-mode

```ruby
line1
line2
line3
```
if mark first line as region, comment, will result in:
```ruby
# line1
line2
line3
```

then mark first + second line as region:
```ruby
# # line1
# line2
line 3
```

it work well for me many years.
