### ISSUE TITLE
Faulty fontification for SCSS Comments

### ISSUE THREAD

**Issue by dustinpaluch** [fxbois/web-mode#598]
[SCSS supports two styles of comments](http://sass-lang.com/documentation/file.SCSS_FOR_SASS_USERS.html#comments): regular CSS comments like `/* this */`, and one-liner comments `// like this`. Currently, web-mode doesn't appear to recognize this second SCSS-specific style.

    /* standard CSS comment */
    // single-line SCSS comment
    body {
    	background: red;
    }

![screen shot 2015-10-02 at 8 46 52 am](https://cloud.githubusercontent.com/assets/6547887/10248007/71570dd4-68e2-11e5-8b34-fe58dd33c85c.png)

(This is in a plain .scss file)

**Comment by fxbois** [comment]
@dustinpaluch I've pushed a fix

**Comment by dustinpaluch** [comment]
Sweet! Looks great when I *paste* my example code into an empty .scss file. I've spotted some related bugs though. Try this:

1. Open a new .scss file
2. Type (do not paste) `/* test */` on the first line

After typing in the closing tag, web-mode-css-comment-face is not applied.

**Comment by fxbois** [comment]
@dustinpaluch please test the last version

**Comment by dustinpaluch** [comment]
@fxbois Fontification for single line SCSS comments appears to be working correctly now. Thank you! The bug I cited in my previous comment is also fixed for plain .css files, but there is still a failing edge case: Fontification still fails when typing a plain CSS comment into an *empty* .scss file.

**Comment by fxbois** [comment]
@dustinpaluch I think I do not understand what you mean. Can you detail all the steps to trigger the bug please

**Comment by dustinpaluch** [comment]
@fxbois Here is a video demo:
http://cl.ly/dYla
The steps to reproduce are:
1. Create and open a new .scss file
2. On the first line, type a standard css comment /* like this */
3. Add more valid (S)CSS below.

Admittedly, I haven't tried this with emacs -q. I will do so if you can't reproduce the bug. For the heck of it, here's my web-mode-debug:

    --- WEB-MODE DEBUG BEG ---
    versions: emacs(24.5) web-mode("12.3.5")
    vars: engine("none") minor("none") content-type("css") file("/Users/imacintel/test.scss")
    system: window(ns) config("x86_64-apple-darwin13.4.0")
    colors: fg(nil) bg(nil) 
    minor modes: (ido-everywhere ido-vertical-mode projectile-mode projectile-global-mode global-auto-revert-mode shell-dirtrack-mode async-bytecomp-package-mode global-git-commit-mode diff-auto-refine-mode emmet-mode highlight-changes-visible-mode ivy-mode)
    vars:
    web-mode-enable-current-column-highlight=nil 
    web-mode-enable-current-element-highlight=nil 
    indent-tabs-mode=t 
    --- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment]
I can not reproduce the bug. Please test with a minimal .emacs

**Comment by dustinpaluch** [comment]
After restarting Emacs, I can no longer reproduce the bug. I thought reloading my init file and toggling web-mode off and on again would be enough, but I guess not. Sorry for wasting your time!
